"""changed nullability on user

Revision ID: 246a659bee60
Revises: 88877125bb5f
Create Date: 2026-05-22 11:49:32.265633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '246a659bee60'
down_revision: Union[str, Sequence[str], None] = '88877125bb5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'annual_consumption_kwh',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('3500'))
    op.alter_column('users', 'load_profile_type',
               existing_type=sa.VARCHAR(length=24),
               nullable=False,
               existing_server_default=sa.text("'SLP'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'load_profile_type',
               existing_type=sa.VARCHAR(length=24),
               nullable=True,
               existing_server_default=sa.text("'SLP'::character varying"))
    op.alter_column('users', 'annual_consumption_kwh',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('3500'))
    # ### end Alembic commands ###
