"""added PVMonthlyProfileFallback for celery job which creates fallback PV profile

Revision ID: c8a915f8df96
Revises: d52982b55aaa
Create Date: 2026-05-28 09:45:48.672902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a915f8df96'
down_revision: Union[str, Sequence[str], None] = 'd52982b55aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if inspector.has_table('pv_monthly_profile_fallback'):
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pv_monthly_profile_fallback',
    sa.Column('pv_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('energy_wh_avg', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pv_id'], ['photovoltaik.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pv_id', 'month', 'hour')
    )
    op.create_index(op.f('ix_pv_monthly_profile_fallback_pv_id'), 'pv_monthly_profile_fallback', ['pv_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if not inspector.has_table('pv_monthly_profile_fallback'):
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pv_monthly_profile_fallback_pv_id'), table_name='pv_monthly_profile_fallback')
    op.drop_table('pv_monthly_profile_fallback')
    # ### end Alembic commands ###
