"""chagend to timezone sensitive in DynamicPricePoints

Revision ID: d52982b55aaa
Revises: f88d5353d8a1
Create Date: 2026-05-26 12:06:52.946382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd52982b55aaa'
down_revision: Union[str, Sequence[str], None] = 'f88d5353d8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    is_timestamptz = bind.execute(
        sa.text(
            """
            SELECT data_type = 'timestamp with time zone'
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = 'dynamic_price_points'
              AND column_name = 'timestamp'
            """
        )
    ).scalar_one_or_none()

    if is_timestamptz:
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dynamic_price_points', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    is_timestamptz = bind.execute(
        sa.text(
            """
            SELECT data_type = 'timestamp with time zone'
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = 'dynamic_price_points'
              AND column_name = 'timestamp'
            """
        )
    ).scalar_one_or_none()

    if is_timestamptz is False:
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dynamic_price_points', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
