"""t

Revision ID: f88d5353d8a1
Revises: 246a659bee60
Create Date: 2026-05-22 12:50:35.122204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f88d5353d8a1'
down_revision: Union[str, Sequence[str], None] = '246a659bee60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


MARKETZONE_VALUES = (
    'AT', 'BE', 'CH', 'CZ', 'DE_LU', 'DE_AT_LU', 'DK1', 'DK2',
    'FR', 'HU', 'IT_North', 'NL', 'NO2', 'PL', 'SE4', 'SI'
)

# Create the PostgreSQL enum once via the first table, and reuse it later without
# issuing a second CREATE TYPE statement.
MARKETZONE_ENUM = postgresql.ENUM(*MARKETZONE_VALUES, name='marketzone', create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    MARKETZONE_ENUM.create(op.get_bind(), checkfirst=True)

    op.create_table('dynamic_price_points',
    sa.Column('market_zone', MARKETZONE_ENUM, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('market_zone', 'timestamp')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=70), nullable=False),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('annual_consumption_kwh', sa.Float(), nullable=False),
    sa.Column('load_profile_type', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('battery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('kw_peak_charge', sa.Float(), nullable=False),
    sa.Column('kw_peak_discharge', sa.Float(), nullable=False),
    sa.Column('kwh', sa.Float(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electric_vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ev_name', sa.String(), nullable=True),
    sa.Column('kw_peak_loading', sa.Float(), nullable=False),
    sa.Column('kwh_battery', sa.Float(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electricity_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_typ', sa.Enum('fixed', 'dynamic_EPEX', name='pricetyp'), nullable=False),
    sa.Column('fixed_price', sa.Float(), nullable=True),
    sa.Column('market_zone', MARKETZONE_ENUM, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_owner_name')
    )
    op.create_table('optimization_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('objective_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_run_day'), 'optimization_run', ['day'], unique=False)
    op.create_index(op.f('ix_optimization_run_user_id'), 'optimization_run', ['user_id'], unique=False)
    op.create_table('photovoltaik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('declination', sa.Float(), nullable=False),
    sa.Column('azimuth', sa.Float(), nullable=False),
    sa.Column('kw_peak', sa.Float(), nullable=False),
    sa.Column('einspeiseverguetung', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photovoltaik_id'), 'photovoltaik', ['id'], unique=False)
    op.create_index(op.f('ix_photovoltaik_owner_id'), 'photovoltaik', ['owner_id'], unique=False)
    op.create_table('token',
    sa.Column('jti_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('jti_family', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jti_id')
    )
    op.create_table('dispatch_point',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('component_type', sa.String(length=30), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('p_charge_kw', sa.Float(), nullable=False),
    sa.Column('p_discharge_kw', sa.Float(), nullable=False),
    sa.Column('soc_kwh', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['optimization_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'ts', 'component_type', 'component_id')
    )
    op.create_table('ev_downtime_exception',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ev_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['ev_id'], ['electric_vehicle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ev_downtime_exception_day'), 'ev_downtime_exception', ['day'], unique=False)
    op.create_index(op.f('ix_ev_downtime_exception_ev_id'), 'ev_downtime_exception', ['ev_id'], unique=False)
    op.create_table('ev_downtime_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ev_id', sa.Integer(), nullable=False),
    sa.Column('weekdays_mask', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('soc_target_start_pct', sa.Float(), nullable=True),
    sa.Column('soc_target_end_pct', sa.Float(), nullable=True),
    sa.Column('tz_name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['ev_id'], ['electric_vehicle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ev_downtime_rule_ev_id'), 'ev_downtime_rule', ['ev_id'], unique=False)
    op.create_table('pv_forecast',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('pv_id', sa.Integer(), nullable=False),
    sa.Column('pv_owner_id', sa.Integer(), nullable=False),
    sa.Column('requested_api', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_day', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pv_id'], ['photovoltaik.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pv_owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_pv_forecast_target_day'), 'pv_forecast', ['target_day'], unique=False)
    op.create_table('pv_forecast_point',
    sa.Column('id_run', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('energy_wh', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_run'], ['pv_forecast.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_run', 'ts')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pv_forecast_point')
    op.drop_index(op.f('ix_pv_forecast_target_day'), table_name='pv_forecast')
    op.drop_table('pv_forecast')
    op.drop_index(op.f('ix_ev_downtime_rule_ev_id'), table_name='ev_downtime_rule')
    op.drop_table('ev_downtime_rule')
    op.drop_index(op.f('ix_ev_downtime_exception_ev_id'), table_name='ev_downtime_exception')
    op.drop_index(op.f('ix_ev_downtime_exception_day'), table_name='ev_downtime_exception')
    op.drop_table('ev_downtime_exception')
    op.drop_table('dispatch_point')
    op.drop_table('token')
    op.drop_index(op.f('ix_photovoltaik_owner_id'), table_name='photovoltaik')
    op.drop_index(op.f('ix_photovoltaik_id'), table_name='photovoltaik')
    op.drop_table('photovoltaik')
    op.drop_index(op.f('ix_optimization_run_user_id'), table_name='optimization_run')
    op.drop_index(op.f('ix_optimization_run_day'), table_name='optimization_run')
    op.drop_table('optimization_run')
    op.drop_table('electricity_price')
    op.drop_table('electric_vehicle')
    op.drop_table('battery')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('dynamic_price_points')
    # ### end Alembic commands ###
