name: CI

on:
  pull_requests:
  push:
    branch: [main]

jobs:
  frontend:
    name: Frontend lint and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: "22"
          cache: "npm"
      - name: Frontend deps
        run: npm ci

      - name: Lint Frontend
        run: npm run lint

      - name: build frontend
        run: npm run build
  
  backend-unit:
    name: backend unit testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: python -m pip install --upgrade pip
              pip install -r requirements.txt
              pip install pytest pytest-asyncio httpx

      - name: Run Unit tests
        run: pytest tests -q -k "not integration tests"
  
  backend-integration:
    name: Backend integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install backend dependencies
        run: python -m pip install --upgrade pip
              pip install -r requirements.txt
              pip install pytest pytest-asyncio

      - name: Start integration dependency
        run: docker compose -f  docker-compose.integration.yml up -d --wait

      - name: Run integration tests
        env: 
          RUN_INTEGRATION: "1"
          DATABASE_URL: postgresql://gridpilot:gridpilot@127.0.0.1:5433/gridpilot_test
          REDIS_URL: redis://127.0.0.1:6380/0
        run: pytest tests/integration -q

      